name: task_tuqaatech
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pixel_perfect: ^1.1.1
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.2
  image_picker: ^0.8.5+3
  permission_handler: ^9.2.0
  flutter_launcher_icons: ^0.9.2
  firebase_messaging: ^11.4.1
  shared_preferences: ^2.0.15
  bmnav_null_safety: ^1.0.1
  sliding_clipped_nav_bar: ^3.1.0+1
  firebase_core: ^1.17.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/Screenshots/
    - assets/icon.png


